# Generated by Django 4.2.16 on 2024-11-02 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
